name: Quotes API Call Auto-Update

# Controls when the action will run. Triggers the workflow on the first of every month
on:
  workflow_dispatch:
  schedule: 
  - cron: "15 14 1 * *"

# Action: Fetch API Data - saves data to fetch_api_data env variable and .json file located in 'fetch-api-data-action/data.json'
jobs:
  refresh-feed:
      runs-on: ubuntu-latest
      steps:
        - name: Checkout
          uses: actions/checkout@v2
          with:
            persist-credentials: false      
        
        - name: Fetch API Data
          uses: JamesIves/fetch-api-data-action@releases/v1
          with:
            ENDPOINT: https://programming-quotes-api.herokuapp.com/quotes/random
            
        - name: Build and Deploy
          uses: JamesIves/github-pages-deploy-action@releases/v3
          with:
            ACCESS_TOKEN: ${{ secrets.ACCESS_TOKEN }}
            BRANCH: master # Pushes the updates to the master branch.
            FOLDER: fetch-api-data-action
            TARGET_FOLDER: quote_string
